/**
 * Types for the Outreach Agent.
 *
 * Models personalized consultive outreach packages generated by
 * OutreachAgent for VRASHOWS enterprise lead engagement.
 *
 * Designed to consume LeadProfile from futurecom-researcher
 * and produce channel-ready communication assets.
 */
import type { LeadProfile } from "../futurecom-researcher/types.js";

// ─── Channel & tone ───────────────────────────────────────────────────────────

export type OutreachChannel = "email" | "linkedin" | "both";

export type OutreachTone =
  | "consultive"   // peer-level, strategic, no sales pressure (default)
  | "direct"       // brief and assertive — for high-score, time-sensitive leads
  | "referral";    // leverages a mutual contact or known case as opener

// ─── Email ────────────────────────────────────────────────────────────────────

export interface ColdEmail {
  /** Subject line — max 8 words, non-promotional */
  subject: string;

  /** Full email body — 120–180 words */
  body: string;

  /** Standalone CTA sentence — extracted for A/B testing */
  cta: string;
}

// ─── LinkedIn ─────────────────────────────────────────────────────────────────

export interface LinkedInMessage {
  /** Message body — 60–90 words */
  body: string;

  /** Standalone CTA sentence */
  cta: string;

  /** Short connection request note (≤300 chars) for cold connect */
  connectionNote: string;
}

// ─── Full outreach package per company ───────────────────────────────────────

export interface OutreachPackage {
  /** Company name (mirrors LeadProfile.company) */
  company: string;

  /** Lead score at time of outreach generation */
  leadScore: number;

  /** Generated cold email */
  coldEmail: ColdEmail;

  /** Generated LinkedIn message */
  linkedinMessage: LinkedInMessage;

  /** The recommended meeting CTA for this lead */
  meetingCta: string;

  /**
   * How VRASHOWS should frame the first conversation.
   * Includes the angle to open with and the operational narrative.
   */
  strategicPositioning: string;

  /**
   * What makes this outreach specific to this company.
   * Used by sales team for context before reaching out.
   */
  personalizationNotes: string;

  /** ISO timestamp of generation */
  generatedAt: string;
}

// ─── Session result ───────────────────────────────────────────────────────────

export interface OutreachResult {
  /** Leads processed in this session */
  leadsProcessed: number;

  /** Outreach packages successfully generated */
  packages: OutreachPackage[];

  /** Any leads that failed generation (company name + reason) */
  failures: Array<{ company: string; reason: string }>;

  /** ISO timestamp of session start */
  sessionStartedAt: string;

  /** ISO timestamp of session end */
  sessionCompletedAt: string;
}

// ─── Input options ────────────────────────────────────────────────────────────

export interface OutreachOptions {
  /** Channel(s) to generate (default: "both") */
  channel?: OutreachChannel;

  /** Outreach tone (default: "consultive") */
  tone?: OutreachTone;

  /**
   * Context about the target event — injected into personalization.
   * Default: "Futurecom 2026"
   */
  event?: string;

  /**
   * Optional sender name for email signature.
   * Default: "VRASHOWS"
   */
  senderName?: string;

  /**
   * Skip leads below this score (default: 40).
   * Prevents wasting outreach on low-fit leads.
   */
  minScore?: number;
}

// ─── Single-lead request (for orchestration) ─────────────────────────────────

export interface OutreachRequest {
  lead: LeadProfile;
  options?: OutreachOptions;
}
